Map<String, String> ar = {
  'toshiba': 'توشيبا',
  'zanussi': 'زانوسي',
  'kiriazi': 'كريازي',
  'samsung': 'سامسونج',
  'lg': 'ال جي',
  'sharp': 'شارب',
  'whiteWhale': 'ويت وايل',
  'whitePoint': 'وايت بونيت',
  'hoover': 'هووفر',
  'daewoo': 'دايو',
  'ariston': 'اريستون',
  'fridge': 'ثلاجات',
  'washer': 'غسالات',
  'electricStove': 'بوتجازات',
  'deepFreezer': 'ديب فريزر',
  'tv': 'شاشات',
  'heater': 'سخان',
  'microwave': 'ميكروويف',
};
